name: Daily Umbrella Check

on:
  schedule:
    # Run at 7:00 AM EST (12:00 PM UTC) every day
    # Adjust the cron schedule based on your timezone
    # Format: minute hour day month day-of-week
    - cron: '0 12 * * *'

  # Allow manual triggering for testing
  workflow_dispatch:

jobs:
  check-weather:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run umbrella advisor
        env:
          WEATHER_API_KEY: ${{ secrets.WEATHER_API_KEY }}
          LOCATION: ${{ secrets.LOCATION }}
          SMTP_SERVER: ${{ secrets.SMTP_SERVER }}
          SMTP_PORT: ${{ secrets.SMTP_PORT }}
          SENDER_EMAIL: ${{ secrets.SENDER_EMAIL }}
          SENDER_PASSWORD: ${{ secrets.SENDER_PASSWORD }}
          RECIPIENT_EMAIL: ${{ secrets.RECIPIENT_EMAIL }}
        run: |
          python umbrella_advisor.py

      - name: Report status
        if: always()
        run: |
          if [ $? -eq 0 ]; then
            echo "✓ Umbrella check completed successfully"
          else
            echo "✗ Umbrella check failed"
            exit 1
          fi
